# Generated by Django 5.1 on 2026-02-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_notification',
            field=models.BooleanField(default=True, verbose_name='通知を受け取る'),
        ),
    ]
